name: Automatic Review Request

on:
    pull_request:
        types: [opened, ready_for_review, reopened]

jobs:
    auto-request-review:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Request reviewers
              run: |
                  PR_NUMBER=${{ github.event.pull_request.number }}
                  REPO_OWNER=${{ github.repository_owner }}
                  REPO_NAME=${{ github.repository }}
                  TOKEN=${{ secrets.GITHUB_TOKEN }}

                  curl -L -X POST \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer $TOKEN" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pulls/$PR_NUMBER/requested_reviewers \
                    -d '{"reviewers":["davydocsurg","juniorbuba"],"team_reviewers":["justice-league"]}'
